package:
    name: place
    version: "0.2.4"

source:
    path: .

requirements:
    build:
        - python >=3.5
        - setuptools

    run:
        - python >=3.5
        - httplib2
        - obspy
        - numpy >=1.0.0
        - scipy
        - matplotlib
        - h5py
        - pyserial
        - websockets

test:
    requires:
        - lxml
    source_files:
        - place/test/*

about:
    home: https://github.com/PALab/place
    license: LGPLv3
    license_file: COPYING

