package:
    name: place
    version: "0.4.0"

source:
    path: .

build:
    number: 28

requirements:
    build:
        - python
        - pyserial
        - pyyaml
        - setuptools
        - pylint

    run:
        - python >=3.5
        - numpy
        - scipy
        - matplotlib
        - pyserial
        - websockets

test:
    requires:
        - python >=3.5
        - numpy
        - scipy
        - matplotlib
        - pyserial
        - websockets
        - pylint

about:
    home: https://github.com/PALab/place
    license: LGPLv3
    license_file: COPYING

