package:
    name: place
    version: "0.3.1"

source:
    path: .

build:
    number: 198

requirements:
    build:
        - python >=3.5,<3.6
        - numpy >=1.0.0
        - scipy
        - matplotlib
        - pyserial
        - websockets
        - mpld3
        - pyyaml
        - setuptools
        - pylint

    run:
        - python >=3.5,<3.6
        - numpy >=1.0.0
        - scipy
        - matplotlib
        - pyserial
        - websockets
        - mpld3

test:
    requires:
        - python >=3.5,<3.6
        - numpy >=1.0.0
        - scipy
        - matplotlib
        - pyserial
        - websockets
        - mpld3
        - pylint

about:
    home: https://github.com/PALab/place
    license: LGPLv3
    license_file: COPYING

