package:
    name: place
    version: "0.3.1"

source:
    path: .

build:
    number: 47

requirements:
    build:
        - python >=3.5
        - numpy >=1.0.0
        - scipy
        - matplotlib
        - obspy
        - h5py
        - pyserial
        - websockets
        - setuptools
        - pylint

    run:
        - python >=3.5
        - numpy >=1.0.0
        - scipy
        - matplotlib
        - obspy
        - h5py
        - pyserial
        - websockets

test:
    requires:
        - python >=3.5
        - numpy >=1.0.0
        - scipy
        - matplotlib
        - obspy
        - h5py
        - pyserial
        - websockets
        - pylint

about:
    home: https://github.com/PALab/place
    license: LGPLv3
    license_file: COPYING

