package:
    name: place
    version: "{{ load_setup_py_data().version }}"

source:
    path: .

build:
    number: 23

requirements:
    build:
        - python
        - pyserial
        - pyyaml
        - setuptools
        - pylint

    run:
        - python >=3.5
        - numpy
        - scipy
        - matplotlib
        - Flask
        - celery
        - django
        - pyserial

test:
    requires:
        - python >=3.5
        - numpy
        - scipy
        - matplotlib
        - Flask
        - celery
        - django
        - pyserial
        - pylint

about:
    home: https://github.com/PALab/place
    license: LGPLv3
    license_file: COPYING

